export { default as Category } from './Category'
export { default as Dashboard } from './Dashboard'
export { default as Home } from './Home'
export { default as NewPost } from './NewPost'
export { default as PostDetails } from './PostDetails'
export { default as Posts } from './Posts'
export { default as EditPost } from './EditPost'